/* exported LATEST_STABLE_VERSION */
module.LATEST_STABLE_VERSION = "4.0.2";
/* exported LATEST_DEVELOPMENT_VERSION */
module.LATEST_DEVELOPMENT_VERSION = "4.16";
/* exported LATEST_STAGING_VERSION */
module.LATEST_STAGING_VERSION = "4.16";
/* exported LATEST_DOS_SUPPORT_VERSION */
module.LATEST_DOS_SUPPORT_VERSION = "4.0";
