---
extends:
  - eslint:recommended

env:
  nashorn: true

rules:
  valid-jsdoc: 2
  comma-spacing:
    - 2
    - {before: false, after: true}
  keyword-spacing:
    - 2
    - {before: true, after: true}
  space-before-function-paren:
    - 2
    - {anonymous: always, named: never, asyncArrow: always}
  no-trailing-spaces: 2
  indent:
    - 2
    - 4
    - {SwitchCase: 1, ArrayExpression: first}
  camelcase:
    - {properties: always}

globals:
  include: false
  TYPE_ID: false
  CATEGORY_ID: false
  APPLICATION_ID: false
  # java
  Bean: false
  # files
  ls: false
  mkdir: false
  fileExists: false
  cat: false
  cp: false
  getFileSize: false
  fileName: false
  lns: false
  remove: false
  touch: false
  tr: false
  writeToFile: false
  createTempFile: false
  # classes
  AppResource: false
  CabExtract: false
  Checksum: false
  Downloader: false
  Engine: false
  Extractor: false
  InstallationType: false
  Resource: false
  SetupWizard: false
  Wine: false
  WineShortcut: false
  # quick scripts
  CustomInstallerScript: false
  InstallerScript: false
  LocalInstallerScript: false
  OnlineInstallerScript: false
  QuickScript: false
  SteamScript: false
  UplayScript: false
  ZipScript: false
  # wine
  LATEST_DEVELOPMENT_VERSION: false
  LATEST_STABLE_VERSION: false
  LATEST_STAGING_VERSION: false
  WINE_PREFIX_DIR: false
