---
extends:
  - eslint:recommended

env:
  nashorn: true

globals:
  include: false
  TYPE_ID: false
  CATEGORY_ID: false
  APPLICATION_ID: false
  # java
  Bean: false
  # files
  mkdir: false
  fileExists: false
  cat: false
  cp: false
  getFileSize: false
  fileName: false
  lns: false
  remove: false
  touch: false
  tr: false
  writeToFile: false
  createTempFile: false
  # classes
  AppResource: false
  CabExtract: false
  Checksum: false
  Downloader: false
  Extractor: false
  Resource: false
  SetupWizard: false
  Wine: false
  WineShortcut: false
  # quick scripts
  CustomInstallerScript: false
  InstallerScript: false
  LocalInstallerScript: false
  OnlineInstallerScript: false
  QuickScript: false
  SteamScript: false
  UplayScript: false
  ZipScript: false
  # wine
  LATEST_DEVELOPMENT_VERSION: false
  LATEST_STABLE_VERSION: false
  LATEST_STAGING_VERSION: false
  WINE_PREFIX_DIR: false
