---
extends:
  - eslint:recommended

env:
  nashorn: true
  es6: true

rules:
  valid-jsdoc: 2
  comma-spacing:
    - 2
    - {before: false, after: true}
  keyword-spacing:
    - 2
    - {before: true, after: true}
  space-before-function-paren:
    - 2
    - {anonymous: always, named: never, asyncArrow: always}
  no-trailing-spaces: 2
  object-curly-spacing:
    - 2
    - always
  indent:
    - 2
    - 4
    - {SwitchCase: 1, ArrayExpression: first}
  camelcase:
    - 2
    - {properties: always}
  linebreak-style:
    - 2
    - unix
  prefer-arrow-callback: 2
  no-var:
    - 2
  prefer-const:
    - 2

globals:
  include: false
  TYPE_ID: false
  CATEGORY_ID: false
  APPLICATION_ID: false

  # java
  Bean: false

  # translations
  tr: false

  # classes
  InstallationType: false
  SetupWizard: false

  # module system
  module: false
