before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-jsonschema python-pil

script:
  - python ./validate.py

after_success:
  # push translation updates only for master (PR changes must be committed to master before they are taken into account)
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./i18n/push_translations.sh; fi

env:
  global:
    - secure: "1TcxUuqZNjbcLlSW7PgxLnZGCBQRv93EJx2N/hwTOiyoiMo/mE3dizmTzyCsvzjp4S3xDbTezPQfbGWeWZTbakrR4zdWz08dZs9+GOZiGiQTtNQfy+XrbmsmDGnYlZIgQ26m35oQkd5Y1ALIkI363za/gzaeeRIJ+jt0IE9Ph16gwfODKBx0HNcLQ6n4AEkPfZB5j4x3rLbWmrUs/Mr0GYUMfZE5BLHjxsR3mX8qxCzHfKQkP/UOQMtuQ5RvPD89eg5k7L5+oAeS9Kz/qzeMRIRV7XFmNu14msSkCVwUfRd47zgsppuqQi5SqJEJZXchSjAiHvUMs6UKQl9vSO7yQiS+iYZSAeoifaAllte57RCHGOW6ep3+kkP0OhZ4iBMJ4ubZ3sBzkCguWwVB38mWWM2r2WSf3ADdLOI4caGLnbH5rr2ITWeDq8FqsiA46A/LK4AsYDU5wqHvME/SQOtU8ygCGZcTF+mVS/CbBTaRMmJ6JtBn2ds7OXp76waYX0hALoWiqE4YYtOwJjdwihWmvFtOBeU/zG9D6nYz19WTFVLTSoYPLYlMQ+kuwhfikNRWMEmq8Do94Gblw/UkC6s7OFMZi7UNuz1s+QF6wt/lewgabWzL+TSXatC2FqKXh62ZbHf5SjT08wZDmqaz+G/DsAB7/G3zaUDPlCC+T0VbQEQ="
