title                    : Phoenicis Scripts Documentation
name                     : phoenicis.org
description              : The documentation for Phoenicis scripts.
repository               : PhoenicisOrg/scripts

remote_theme             : mmistakes/minimal-mistakes
minimal_mistakes_skin    : air

markdown                 : kramdown
permalink                : /:categories/:title/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-remote-theme

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

include:
  - _pages

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
  
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"

author:
  name:   Phoenicis
  github: PhoenicisOrg

# HTML Compression
compress_html:
  clippings: all
