name: PR Review

on: pull_request

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          level: error
          fail_on_error: true
          reporter: github-pr-review
          eslint_flags: '-c .eslintrc.yml ./**/*.js'
